FORMAT: 1A

# Axentro API
The following information gives an overview of the Axentro API

## Overview

The Axentro blockchain platform is an original proof of work blockchain that blends slow blocks and fast blocks into a single chain to provide a range of functionality. Axentro aims to provide a platform for building decentralised apps cheaply and quickly.

### Using the API

The API is available on either HTTP or HTTPS but we recommend you use HTTPS for posting transactions. No authorisation is required to use the API. The API is designed loosely following REST principles and functions like any other web API.


{{ partial "blockchain-info.apib" }}

{{ partial "block.apib" }}

{{ partial "transaction.apib" }}

{{ partial "address.apib" }}

{{ partial "wallet.apib" }}

{{ partial "domain.apib" }}

{{ partial "hra.apib" }}

{{ partial "tokens.apib" }}

{{ partial "search.apib" }}

{{ partial "node.apib" }}