## Group Domain

# /domain/{domain}

## GET

This retrieves amounts of tokens for a domain as Json

+ Parameters
    + domain (string) - The domain
    
+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                {
                  "confirmation": 1,
                  "pairs": 
                    [
                      {
                        "token": "AXNT",
                        "amount": "19.68043428"
                      },
                      {
                        "token": "EAGLE",
                        "amount": "0"
                      }
                    ]
                }
            }

        
## domain/transactions [GET /domain/{domain}/transactions{?page}{?per_page}{?direction}{?sort_field}{?actions}]

This retrieves the transactions for a domain as Json

+ Parameters
    + domain (string) - The domain
    + page: 0 (number, optional) - The page
    + per_page: 20 (number, optional) - The number of items per page
    + direction: up (string, optional) - The direction (up = ascending, down = descending)
    + sort_field: time (string, optional) - The sort field (id = transactionId, time = transaction timestamp)
    + actions (string, optional) - actions to filter in a comma delimited list e.g `?send,head`
    
+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": {
                "transactions": [
                  "transaction":
                    {
                      "id": "09b05cb672911ba03a1e3372a58348e61a0b267efdc8ee89df59978037d19523",
                      "action": "head",
                      "senders": [],
                      "recipients": 
                        [
                          {
                            "address": "VDBjMjI1ZmE0MmQzYTAwYWJlZGNjMTFkNzQ5YjMxZGFkNGVhYjU2N2YwNzFmYjFk",
                            "amount": 299904068
                          },
                          {
                            "address": "VDA2NjU5N2JlNDA3ZDk5Nzg4MGY2NjY5YjhhOTUwZTE2M2VmNjM5OWM2M2EyMWQz",
                            "amount": 899712202
                          }
                        ],
                      "message": "0",
                      "token": "AXNT",
                      "prev_hash": "0",
                      "timestamp": 1569910322451,
                      "scaled": 1,
                      "kind": "SLOW",
                      "version": "V1"
                    },
                    "confirmations": 1,
                    "block_id": 2
                ],
                "pagination": {
                  "page": 0,
                  "per_page": 20,
                  "direction": 1,
                  "sort_field": 0,
                  "count": 1,
                  "total_count": 1
                }
              }  
            }

## domain/amount/token [GET /domain/{domain}/token/{token}]

This retrieves the amount for a specified token for a domain as Json

+ Parameters
    + domain (string) - The domain
    + token (string) - The token
    
+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                {
                  "confirmation": 1,
                  "pairs": 
                    [
                      {
                        "token": "AXNT",
                        "amount": "19.68043428"
                      }
                    ]
                }
            }