## Group Node

# /node

## GET

Show information about the current node
    
+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                {
                  "id": "0bd4b62baa97bf1ac608ae311d41c0b6",
                  "host": "testnet.axentro.io",
                  "port": 3000,
                  "ssl": false,
                  "type": "testnet",
                  "is_private": false,
                  "address": ""
                }
            }

        
## node/id [GET /node/{id}]

Show information about the specified node id

+ Parameters

    + id (number) - The node id
    
+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                {
                  "id": "0bd4b62baa97bf1ac608ae311d41c0b6",
                  "host": "testnet.axentro.io",
                  "port": 3000,
                  "ssl": false,
                  "type": "testnet",
                  "is_private": false,
                  "address": ""
                }
            }

## node/address/{address} [GET /node/address/{address}]

Find a node with the specified wallet address

+ Parameters

    + address (string) - The wallet address of the node
    
+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                {
                  "id": "0bd4b62baa97bf1ac608ae311d41c0b6",
                  "host": "testnet.axentro.io",
                  "port": 3000,
                  "ssl": false,
                  "type": "testnet",
                  "is_private": false,
                  "address": ""
                }
            }

## nodes [GET /nodes]

Show information about the connecting nodes

+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                {
                  "successor_list": [],
                  "predecessor": null,
                  "private_nodes": 
                    [
                      {
                        "id": "faec239b8eebf72ff73783eaf72762bd",
                        "host": "",
                        "port": -1,
                        "ssl": false,
                        "type": "testnet",
                        "is_private": true,
                        "address": ""
                      }
                    ],
                  "finger_table": []  
                }
            }

## node/official_nodes [GET /node/official_nodes]

Show information about the connecting nodes

+ Response 200 (application/json)

    + Body

            {
              "status":"success",
              "result":{
                "all":[
                  "VDBiNGU3OGRjYzUzYTFjMjAwNmZiMzNmMTA0NTVhZmViZjY1MWI2ODQ0NWJjMDIy"
                ],
                "online":[
                {
                 "id":"5fecec2d9abeaabc24603f69f8debe80",
                 "address":"VDBiNGU3OGRjYzUzYTFjMjAwNmZiMzNmMTA0NTVhZmViZjY1MWI2ODQ0NWJjMDIy",
                 "url":"https://localhost:3002"
                }
                ]
              }
            }            