## Group Scars

# /scars/sales

## GET

This shows the list of domains for sale as Json
    
+ Response 200 (application/json)

    + Body

            {
              "result": 
                [
                  {
                    "address": "VDAxNmM1OGVkNmYyNzI2NzcyYjYzODRmMzJmMDkzODhjMTczNWI0NDFjZGM5ZTIz",
                    "domain_name": "awesome.sc",
                    "price": 100,
                    "status": 1
                  },
                  {
                    "address": "VDAxNmM1OGVkNmYyNzI2NzcyYjYzODRmMzJmMDkzODhjMTczNWI0NDFjZGM5ZTIz",
                    "domain_name": "superdry.sc",
                    "price": 100,
                    "status": 1
                  }
                ],
              "status": "success"
            }

        
## scars/domain [GET /scars/{domain}]

This retrieves the status of the scars domain as Json

+ Parameters

    + domain (string) - The domain
    
+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                {
                  "resolved": true,
                  "confirmation": 1,
                  "domain": 
                    {
                      "domain_name": "fullmetal.sc",
                      "address": "VDBkYWQxZjZlZjllOTAzYzNiODQ0NmZkZTI4NDBhYmMzYjUxYThjM2E1ZjNkODlj",
                      "status": 0,
                      "price": "0"
                    }
                }
            }


## scars/lookup [GET /scars/lookup/{address}]

This retrieves a list of domains that are mapped to the supplied address

+ Parameters

    + address (string) - The address
    
+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                {
                  "address": "VDAyYjdiOTM0MmNhY2JkNDU2NWViNmMyNmI1OGRhNGI5YTRkY2E5ODIzM2UzOTgx",
                  "domains": 
                    [
                      {
                        "domain_name": "christian.sc",
                        "address": "VDAyYjdiOTM0MmNhY2JkNDU2NWViNmMyNmI1OGRhNGI5YTRkY2E5ODIzM2UzOTgx",
                        "status": 0,
                        "price": "10"
                      },
                      {
                        "domain_name": "christian2.sc",
                        "address": "VDAyYjdiOTM0MmNhY2JkNDU2NWViNmMyNmI1OGRhNGI5YTRkY2E5ODIzM2UzOTgx",
                        "status": 0,
                        "price": "0"
                      }
                    ]
                }
            }
            