## Group Tokens

# /tokens

## GET

Shows a list of all available tokens as Json

+ Response 200 (application/json)

    + Body

            {
              "status": "success",
              "result": 
                [
                  "AXE",
                  "EAGLE"
                ]  
            }