FORMAT: 1A

# SushiChain API
The following information gives an overview of the SushiChain API

{{ partial "blockchain-info.apib" }}

{{ partial "block.apib" }}

{{ partial "transaction.apib" }}

{{ partial "address.apib" }}

{{ partial "domain.apib" }}

{{ partial "scars.apib" }}
